name: Build Nightly Docker Image
on:
  schedule:
    - cron: '0 4 * * *' # 0400 UTC (midnight EST)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: srfrnk/current-time@v1.1.0
        id: time
        with:
          format: YYYYMMDD
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mrothy/go2go
          add_git_labels: true
          tags: ${{ steps.time.outputs.formattedTime }}, latest
          push: true
